site_name: Java Tetris 
theme: readthedocs
repo_url: https://github.com/cs-nku/tetris-java
extra_javascript:
  - extra.js
extra_css:
  - extra.css
pages:
  - Home: index.md
markdown_extensions:
    - admonition:
